### ISSUE TITLE
Completely disable the SDK

### ISSUE THREAD

**Issue by nelletto** [appcues/appcues-android-sdk#517]
We use a configuration system through which we have decided, for the moment, to completely turn off Appcues. However, we noticed that the initialization of a part of the SDK still occurs via `AppcuesInitializer`. Is it possible to have a way to completely deactivate the SDK programmatically (therefore without using `tools:node="remove"`) so that we can activate or deactivate it when we need it?

**Comment by iujames** [comment]
Hi @nelletto - I believe to support this use case, we would need to add a couple of functions in the public API of our SDK to `start(context)` and `stop(context)` these services. A proposed approach is in https://github.com/appcues/appcues-android-sdk/pull/518 , if you would like to give any feedback. Do you think this would address your use case?

**Comment by iujames** [comment]
Hi @nelletto , this update has been merged and a new version `3.1.3` has been published to Maven Central. I'll go ahead and close this issue now. Thanks for your feedback here!
