### ISSUE TITLE
Compose 1.6.0 support

### ISSUE THREAD

**Issue by dominikgold** [appcues/appcues-android-sdk#560]
Hi! We've been enjoying using Appcues, thanks for the great work.

When are you planning to update the SDK to Compose 1.6.0? There's a bunch of features there that we'd really like to use, but when we update our app, certain Appcues flows make the app crash because they rely on some Compose 1.5.x APIs to be present. So until the SDK is updated, we are blocked from updating our app to Compose 1.6.0.

**Comment by andretortolano** [comment]
Hey @dominikgold thanks for reaching out.

we already did a first pass on the update, there are some api changes like you said but also some [Text padding changes](https://medium.com/androiddevelopers/fixing-font-padding-in-compose-text-768cd232425b) that are impacting our composition and we are still looking into that. 

that said as soon as we figure this out we should publish a new version that you can use.

**Comment by andretortolano** [comment]
sorry the delay on this, the new version 3.1.13 is just now available and its using Compose 1.6
