### ISSUE TITLE
ModalStateMachineOwner.onUiIdle java.lang.OutOfMemoryError com.appcues.ui ModalStateMachineOwner.kt:116

### ISSUE THREAD

**Issue by mahmed1987** [appcues/appcues-android-sdk#616]
We get this crash in our production app for a few devices. 

I have printed the stacktrace below

<img width="850" alt="image" src="https://github.com/appcues/appcues-android-sdk/assets/26518062/a70ceeee-4786-4c9a-b18b-05e3f8765adc">

This is the OS breakdown of the crash
<img width="546" alt="image" src="https://github.com/appcues/appcues-android-sdk/assets/26518062/e29380a5-8615-4ca1-b5f7-9b424d516086">

This is the device breakdown
<img width="550" alt="image" src="https://github.com/appcues/appcues-android-sdk/assets/26518062/5aa7cc8f-a0b7-4903-ab12-d1b6928714a1">

**Comment by iujames** [comment]
Hi @mahmed1987 , thank you for letting us know about this issue. We believe it is possible that the use of a Timer could be leading to memory issues in some cases. One idea we have is to change this to use a coroutine and a delay - @andretortolano proposed this change in #617 if you have any feedback to share on that approach. Thanks!

**Comment by mahmed1987** [comment]
@iujames  thanks for quick resolution of the issue . Any idea when this fix would be included in your release cycle ?

**Comment by andretortolano** [comment]
hey @mahmed1987 we plan on doing a small patch that include the fix this afternoon

**Comment by iujames** [comment]
@mahmed1987 confirming that @andretortolano did release the 3.1.14 version yesterday, with this update, and you should see that available now in Maven Central. Thank you @andretortolano !

**Comment by mahmed1987** [comment]
Thanks a bunch good folks. I hope this would resolve the situation. Will update our app with the new dependency and wait for the results

**Comment by mahmed1987** [comment]
@iujames  I forgot to mention that i am using the the appcues dependency through segment 

I am using this to include the appcues sdk in the code 

com.appcues:segment-appcues:3.1.14.

I guess 3.1.14 must be available for com.appcues:appcues but for the above dependency with segment I get the error 

"Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find com.appcues:segment-appcues:3.1.14.
" during dependency resolution .

**Comment by iujames** [comment]
@mahmed1987 got it, thank you for this additional info. We can update our Segment plugin to match, today.

**Comment by iujames** [comment]
@mahmed1987 the Appcues-Segment plugin version 3.1.14 update has been published with this change https://github.com/appcues/segment-appcues-android/releases/tag/3.1.14 .
